.travis.yml
docs/installation.rst
docs/release_notes.rst
runtests.py
setup.py
testproject/testproject/settings/__init__.py
tox.ini
wiki/decorators.py
wiki/managers.py
wiki/migrations/0001_initial.py
wiki/plugins/attachments/migrations/0001_initial.py
wiki/plugins/images/migrations/0001_initial.py
wiki/plugins/notifications/migrations/0001_initial.py
wiki/tests/test_basic.py

Django 1.7 fixes, and other things.
Let me know if you don't want to pull all of them, I can separate out the fixes.

Fix django 17

---

wiki/tests/base.py
wiki/tests/test_basic.py
wiki/tests/test_managers.py

No new asserts, only code refactoring. See names of commits.

Small refactoring of unit tests.

---

wiki/core/http.py

Fix downloading attachments with non-ascii characters

---

wiki/conf/settings.py

Assuming I got the idea right.

Fixes settings.py comment

---

wiki/tests/base.py
wiki/tests/test_template_filters.py
wiki/tests/test_template_tags.py

Look closely at the WikiRenderTest. This tag performs operations with plugins, but for testing purposes I mocked this part.

Tests for template tags.

---

wiki/tests/base.py
wiki/tests/test_models.py
wiki/tests/test_template_filters.py

@benjaoming what do you think?
I also have are few questions:
1 URLPath looks tricky for me. Maybe simply mock this test (mean no library, just monkey patching)?
2 What does "NB" in Article methods doc's mean (I dont have formal CS degree)?

Tests for article model

---

wiki/templates/wiki/includes/pagination.html

Hi everyone,
I just added what I think it's the simplest fix for the pagination problem as pointed out in issue #418. 
I tested it with the 'testproject'.

Search pagination fix

---

.travis.yml
tox.ini

Speaks for itself really. Features in tox 1.8 (2014-09-24) allowed a lot of clean up.

Better tox ini

---

wiki/plugins/images/markdown_extensions.py

Fixes images inside tables so they arent displayed in a new row. Images that were inserted besides text on a single line no longer appear after the text, the text will now wrap around the image.
Edit: Forgot to mention, this patch is in regards to [this issue.](https://github.com/django-wiki/django-wiki/issues/204)
<br/>
<br/>

Patch for image markdown

---

wiki/templates/wiki/base_site.html
wiki/templatetags/wiki_tags.py
wiki/tests/test_template_filters.py
wiki/tests/test_template_tags.py

Also fixing test cases for when Pygments fails. Not adding that to tox.ini, though, because it makes testing a lot slower.

Plugin template tag

---

runtests.py
tox.ini
wiki/core/compat.py
wiki/core/plugins/loader.py
wiki/core/plugins/registry.py
wiki/core/utils.py
wiki/decorators.py
wiki/plugins/attachments/markdown_extensions.py
wiki/plugins/attachments/templates/wiki/plugins/attachments/index.html
wiki/plugins/attachments/views.py
wiki/plugins/images/markdown_extensions.py
wiki/plugins/macros/mdx/macro.py
wiki/tests/base.py
wiki/tests/test_urls.py
wiki/urls.py
wiki/views/article.py

Probably best reviewed one commit at a time, rather than the full diff.

Fix various deprecation warnings on Django 1.7/1.8

---

wiki/plugins/macros/mdx/wikilinks.py

Use correct base path for [[ article-link ]] syntax

---

.travis.yml
setup.py
tox.ini
wiki/plugins/attachments/views.py
wiki/plugins/images/views.py
wiki/tests/base.py
wiki/tests/test_models.py
wiki/tests/test_urls.py
wiki/tests/test_views.py
wiki/views/article.py
wiki/views/mixins.py

Fixes for django 1.9

---

wiki/views/article.py

handle ValueError coming from querystring input

---

wiki/conf/settings.py
wiki/plugins/images/markdown_extensions.py
wiki/plugins/images/templates/wiki/plugins/images/render.html

Cleanup after Markdown: Remove <p> tag from surrounding <figure>

---

setup.py
tox.ini

Add reasonable upper bounds to deps, test latest markdown with tox

---

wiki/admin.py
wiki/models/urlpath.py

Fix #426: Add article raw id field to url path admin and auto-populate articleforobject

---

wiki/plugins/images/models.py

Fix #428: Do not call str()

---

wiki/conf/settings.py

Fix settings naming

---

HISTORY.rst
Makefile
README.rst
docs/release_notes.rst
setup.py
wiki/__init__.py
wiki/core/version.py

I did this a bit wrongly, I normally have stuff merged before I released it, but I've just released my personnal repo as 0.1b0 and here are the changes released.

Prerelease updates 0.1b0

---

wiki/templates/wiki/accounts/login.html

I have noticed a weird title on the login page. There is my tiny fix.

Fix login page title

---

README.rst

i think the url demo  in the readme is false.

good url demo in readme

---

wiki/templates/wiki/base_site.html

Do not display account-related links in menu when WIKI_ACCOUNT_HANDLING=False

---

docs/release_notes.rst
wiki/__init__.py

@duvholt suggesting that we release now :)

Finalize release notes and bump version

---

tox.ini
wiki/models/__init__.py

Fix reopened #424

---

testproject/testproject/views.py

Fixes demo server's 404 and 500 views

Error handling views in testproject should be updated for latest django

---

.gitignore
wiki/tests/test_views.py
wiki/views/accounts.py
wiki/views/article.py

Test of merge preview + fix Django 1.10 issue

---

docs/release_notes.rst
wiki/forms.py
wiki/static/wiki/js/urlify.js
wiki/templates/wiki/create.html
wiki/tests/test_views.py

Fix slug validation behavior

---

docs/release_notes.rst
wiki/views/accounts.py
wiki/views/article.py

Replace render_to_request() with render ()

---

docs/release_notes.rst
wiki/core/markdown/__init__.py

Fix memory leak reported by @obtroston in #609

Fix memory leak reported by @obtroston in #609

---

wiki/core/markdown/mdx/codehilite.py
wiki/tests/test_markdown.py
wiki/tests/test_markdown_plugins.py
wiki/tests/test_template_tags.py

Allow unicode in codehilite + tests

---

docs/release_notes.rst
wiki/models/article.py

Generate article cache key according to currently active language

---

Makefile
docs/conf.py
docs/index.rst
docs/settings.rst
wiki/__init__.py
wiki/conf/settings.py

Documentation for settings

---

docs/release_notes.rst
wiki/templates/wiki/includes/searchresult.html

Render contents (hopefully cached) before displaying search result

---

.travis.yml
CONTRIBUTING.md
Makefile
README.rst
docs/development/environment.rst
docs/development/index.rst
docs/development/testing.rst
docs/development/testproject.rst
docs/index.rst
docs/installation.rst
src/wiki/core/compat.py
src/wiki/models/__init__.py
src/wiki/models/urlpath.py
src/wiki/plugins/attachments/admin.py
src/wiki/plugins/attachments/wiki_plugin.py
src/wiki/plugins/globalhistory/wiki_plugin.py
src/wiki/plugins/help/wiki_plugin.py
src/wiki/plugins/images/admin.py
src/wiki/plugins/images/models.py
src/wiki/plugins/images/wiki_plugin.py
src/wiki/plugins/links/mdx/urlize.py
src/wiki/plugins/links/wiki_plugin.py
src/wiki/plugins/macros/wiki_plugin.py
src/wiki/plugins/notifications/models.py
src/wiki/plugins/notifications/wiki_plugin.py
tests/core/test_urls.py
tox.ini

Fixes #635 
* Adds Developer Guide
* Consolidates README.rst
* Adds new `lint` target (because it was in the Cookiecutter template)
* Fixes a few pep8 issues
* Adds flake8 test to Travis and tox

Developer docs + installation guide update

---

tox.ini

It already does an installation through setup.py
Fixes #633

Remove PYTHONPATH from tox env

---

docs/conf.py
docs/installation.rst

Add section about setting up account handling 

---

src/wiki/models/article.py
tests/core/test_models.py

Mark cache as safe

---

docs/release_notes.rst
src/wiki/views/accounts.py
tests/core/test_accounts.py
tests/settings.py

Fix redirect on account update - replace hardcoded string with referer detection

---

tox.ini

as proposed by @spookylukey in #673

Bump django-functest and django-webtest 

---

.travis.yml
tox.ini

Troubleshooting issue found in #689 Travis tests...

Use Tox-Travis for better support matrix on Travis

---

docs/release_notes.rst
src/wiki/templates/wiki/base_site.html

Supersedes #689 after Travis and Tox reconfiguration

add logout button even if ACCOUNT_HANDLING is not set

---

docs/release_notes.rst
src/wiki/templates/wiki/search.html

Thanks @geoffclapp !
Supercedes #698

Fixing wrong submit type

---

src/wiki/plugins/globalhistory/templates/wiki/plugins/globalhistory/globalhistory.html
src/wiki/templates/wiki/move.html
src/wiki/views/article.py
tests/plugins/globalhistory/test_globalhistory.py

Leftover from #627 and #640 as pointed out by one of the Russian translators.. will update Transifex after merging

Add missing pluralization of 3 msgid...s :)

---

src/wiki/forms.py

String comparison in wiki.forms.clean_slug

---

setup.cfg
src/wiki/core/paginator.py
src/wiki/core/plugins/registry.py
src/wiki/models/article.py
src/wiki/models/pluginbase.py
src/wiki/plugins/attachments/models.py
src/wiki/plugins/images/markdown_extensions.py
src/wiki/plugins/macros/mdx/macro.py
src/wiki/templatetags/wiki_tags.py
src/wiki/views/article.py
tests/core/test_markdown.py
tests/core/test_template_filters.py

Violating Hettinger's PEP8 rule, but the violations of those rules were quite few.

Fix E226, E302, E303 and E41 flake8 errors.

---

docs/release_notes.rst
src/wiki/plugins/links/mdx/djangowikilinks.py
tests/plugins/links/test_links.py

Support fragments in wiki links.

---

requirements_readthedocs.txt
setup.py
src/wiki/core/plugins/registry.py
src/wiki/models/__init__.py
src/wiki/plugins/macros/mdx/macro.py
tox.ini

Not sure about this file `requirements_readthedocs.txt`.

Replaced external six with django.utils.six.

---

src/wiki/core/markdown/__init__.py
src/wiki/models/article.py
src/wiki/templates/wiki/includes/render.html
src/wiki/templatetags/wiki_tags.py

to be able customise render page differently for each user/user's group the user has been added as article's render argument. This change has impact to caching - I add a per-user cache

add user argument to article render

---

src/wiki/plugins/attachments/templates/wiki/plugins/attachments/delete.html
src/wiki/templates/wiki/includes/breadcrumbs.html

@citxx this will break existing translations, so I don't know if you think this is a good idea or not.. I don't have much experience translating, and since I cannot verify existing languages, I don't know if translators are adding bad strings and not objecting like you did :)

Improvements to translation precision

---

src/wiki/plugins/links/views.py

Should have been removed in 384fb62040dbf27805352d83443467ce175c34c8

Removed a meaningless comment in QueryUrlPath.dispatch.

---

.travis.yml
setup.py
src/wiki/core/utils.py
tox.ini

Probably more tests around this should be added.

Simplified wiki.core.utils.object_to_json_response.

---

src/wiki/admin.py
src/wiki/core/markdown/__init__.py
src/wiki/core/markdown/mdx/codehilite.py
src/wiki/core/paginator.py
src/wiki/editors/markitup.py
src/wiki/forms.py
src/wiki/models/pluginbase.py
src/wiki/models/urlpath.py
src/wiki/plugins/attachments/forms.py
src/wiki/plugins/attachments/views.py
src/wiki/plugins/globalhistory/views.py
src/wiki/plugins/images/admin.py
src/wiki/plugins/images/forms.py
src/wiki/plugins/images/models.py
src/wiki/plugins/images/views.py
src/wiki/plugins/notifications/forms.py
src/wiki/plugins/notifications/views.py
src/wiki/views/accounts.py
src/wiki/views/article.py
src/wiki/views/deleted_list.py
src/wiki/views/mixins.py
tests/base.py
tests/core/test_markdown.py
tests/core/test_template_tags.py
tests/plugins/attachments/test_commands.py
tests/plugins/attachments/test_views.py
tests/plugins/images/test_views.py

I left the one instance in #775 be.

Switched to Python 3's super() syntax.

---

src/wiki/plugins/macros/templatetags/wiki_macro_tags.py
src/wiki/templatetags/wiki_tags.py

Extract from https://github.com/django-wiki/django-wiki/pull/755

Use simple_tag as assigned_tag is removed

---

src/wiki/core/permissions.py
src/wiki/decorators.py
src/wiki/forms.py
src/wiki/managers.py
src/wiki/models/article.py
src/wiki/models/urlpath.py
src/wiki/plugins/attachments/models.py
src/wiki/plugins/attachments/views.py
src/wiki/plugins/haystack/__init__.py
src/wiki/plugins/haystack/views.py
src/wiki/plugins/images/models.py
src/wiki/plugins/images/templatetags/wiki_images_tags.py
src/wiki/views/accounts.py
src/wiki/views/article.py

Exctract from https://github.com/django-wiki/django-wiki/pull/755

Added user.is_{authenticated,anonymous} compatibility

---

docs/development/index.rst
setup.py
tests/core/test_accounts.py
tests/core/test_views.py

I also moved them to the `accounts` test module.
CC: @atombrella

Update auth view tests for Django 2.0

---

src/wiki/forms.py
tests/core/test_forms.py

This also reverts some auto-pep8 in those two forms.

Increased test coverage for UserCreation and DeleteForm.

---

src/wiki/core/utils.py
src/wiki/urls.py

Use django import_string instead of get_class_from_str

---

src/wiki/plugins/images/apps.py
src/wiki/plugins/images/checks.py
src/wiki/plugins/images/models.py

@rsalmaso Perhaps you want to check this, since you replaced a similar pattern in the core.

Use AppConfig.ready to check for sorl.thumbnail in images plugin.

---

src/wiki/compat.py
src/wiki/editors/markitup.py
src/wiki/forms.py
src/wiki/templates/wiki/forms/markitup-admin.html
src/wiki/templates/wiki/forms/markitup.html
src/wiki/templates/wiki/forms/select.html
src/wiki/templates/wiki/forms/select_option.html
src/wiki/templates/wiki/forms/text.html

Upgrade to new form widget system

Use template based rendering for custom form widgets

---

src/wiki/models/urlpath.py

I spotted other things that appear to be unnecessary in that class.

Removed an unneeded super().clean in URLPath.

---

src/wiki/templatetags/wiki_tags.py
src/wiki/views/deleted_list.py

Removed unneeded parentheses.

---

src/wiki/decorators.py

I think the policy is undoing auto-pep8 is also fine.

Deleted a redundant initialization in wiki.decorators.get_article.

---

requirements_readthedocs.txt
setup.py
tests/core/test_markdown.py

Upgraded bleach to latest version and fixed tests (issue #702 )

Bleach upgrade

---

src/wiki/plugins/images/models.py

Fixes S3 Storage fix for uninmplemented path method

S3 storage fix

---

src/wiki/plugins/attachments/templates/wiki/plugins/attachments/delete.html
src/wiki/plugins/attachments/templates/wiki/plugins/attachments/index.html
src/wiki/plugins/attachments/templates/wiki/plugins/attachments/replace.html
src/wiki/plugins/globalhistory/templates/wiki/plugins/globalhistory/globalhistory.html
src/wiki/templates/wiki/dir.html
src/wiki/templates/wiki/includes/anonymous_blocked.html
src/wiki/templates/wiki/move.html

Removes unnecessary endline/startline characters from strings

Removes unnecessary endline/startline characters from strings

---

src/wiki/plugins/images/markdown_extensions.py
src/wiki/plugins/macros/mdx/macro.py
src/wiki/plugins/macros/templatetags/wiki_macro_tags.py
tests/plugins/images/test_markdown.py
tests/plugins/macros/test_macro.py

This allows escaping the macros parsed by the macro library.

Allow escaping [image] and [article_list]

---

Makefile
src/wiki/locale/en/LC_MESSAGES/django.po

As ref'ed by @Mortal in #894, the source messages for translations haven't been updated during last Transifex interaction, which is a mistake that's less likely when it's in the Makefile..

Run compilemessages just before pushing to Transfix + update source django.po

---

src/wiki/decorators.py
src/wiki/templates/wiki/permission_denied.html

If read isn't allowed, then display back button to parent article

---

src/wiki/conf/settings.py
src/wiki/templatetags/wiki_tags.py

@dexbleeker @teury - would you have time to review/test this? Thanks :)

Simplification of message tag resolution and setting, fixes #922

---

docs/release_notes.rst
src/wiki/__init__.py
src/wiki/plugins/images/models.py

Fix image revision number null

---

.travis.yml
README.rst
src/wiki/plugins/attachments/markdown_extensions.py
src/wiki/plugins/attachments/views.py
src/wiki/plugins/images/views.py
src/wiki/plugins/links/mdx/urlize.py
src/wiki/plugins/links/views.py
src/wiki/plugins/macros/mdx/wikilinks.py
src/wiki/plugins/notifications/views.py
src/wiki/views/accounts.py
src/wiki/views/article.py
tests/plugins/links/test_urlize.py
tox.ini

`travis.yml` has Django 2.2 in it, so I guess it's left out by mistake?

[WIP] Update version table and testing matrices

---

setup.py

Upgrade pytest

---

src/wiki/forms.py
src/wiki/forms_account_handling.py

All from classes that have coverage.

Removed unneeded calls to Form.clean.

---

docs/release_notes.rst
src/wiki/__init__.py

Release note for #978

---

README.rst

Docker info

---

docs/release_notes.rst
src/wiki/templates/wiki/delete.html

Fix can't delete Article with USE_THOUSAND_SEPARATOR = True #1013

---

docs/conf.py
setup.py
src/wiki/core/markdown/__init__.py

Update Bleach version

---

docs/release_notes.rst
setup.py

Was looking into #1038 but didn't find a fix.

Markdown 3.2 series

---

README.rst

Add note about test/test user

---

docs/release_notes.rst
src/wiki/models/article.py

slugify cache keys because of memcached issue with spaces

---

docs/release_notes.rst
src/wiki/__init__.py

0.7 final release bump

---

src/wiki/models/article.py
tests/core/test_models.py

fixes https://github.com/django-wiki/django-wiki/issues/1072

fix_1072: Fix generation of cache_key

---

docs/release_notes.rst

typo fixed.

---

src/wiki/templates/wiki/base_site.html

Show/suppress "Sign up" link according to ACCOUNT_SIGNUP_ALLOWED setting

---

docs/release_notes.rst
requirements_readthedocs.txt
setup.py

Fixes https://github.com/django-wiki/django-wiki/security/dependabot/setup.py/bleach/open

Upgrade bleach due to security advice

---

src/wiki/decorators.py
src/wiki/plugins/redlinks/mdx/redlinks.py
tests/core/test_urls.py
tests/plugins/macros/test_links.py
tests/plugins/redlinks/test_redlinks.py
tests/settings.py

Addresses, but doesn't fix completely, isssue #1114 
In particular, there is no parameterization over different wiki roots yet, which would be necessary to make sense of several tests.

Re-structure divide between internal and external links

---

docs/release_notes.rst
src/wiki/plugins/links/mdx/urlize.py
tests/plugins/links/test_urlize.py

Rename fa-external-link to fa-external-link-alt

---

.pre-commit-config.yaml
docs/release_notes.rst
src/wiki/forms.py
src/wiki/templates/wiki/accounts/signup.html
tests/base.py
tests/core/test_views.py
tests/testdata/models.py

Ay what a stupid problem and what a simple solution.
Fixes  #1058
Refs #1118 - adds a few more tests, but not sufficient at all.

Settings page broken: got an unexpected keyword argument 'disabled'

---

src/wiki/core/markdown/mdx/codehilite.py
src/wiki/core/markdown/mdx/previewlinks.py
src/wiki/core/markdown/mdx/responsivetable.py
src/wiki/plugins/attachments/markdown_extensions.py
src/wiki/plugins/editsection/markdown_extensions.py
src/wiki/plugins/images/markdown_extensions.py
src/wiki/plugins/macros/mdx/macro.py
src/wiki/plugins/macros/mdx/wikilinks.py
src/wiki/plugins/redlinks/mdx/redlinks.py

I've tried replacing calls for `add()` with `register()` when using Markdown.

Replacing depreciated add() for #1099

---

src/wiki/plugins/notifications/apps.py

Fix local variable issue in notification

---

src/wiki/core/markdown/__init__.py
src/wiki/core/markdown/mdx/codehilite.py
src/wiki/core/markdown/mdx/previewlinks.py
src/wiki/core/markdown/mdx/responsivetable.py
src/wiki/plugins/attachments/markdown_extensions.py
src/wiki/plugins/editsection/markdown_extensions.py
src/wiki/plugins/images/markdown_extensions.py
src/wiki/plugins/macros/mdx/macro.py
src/wiki/plugins/macros/mdx/wikilinks.py
src/wiki/plugins/redlinks/mdx/redlinks.py

I've tried refactoring the repetitive code and reverted the code before #1099

Refactor code for issue #1129

---

src/wiki/models/article.py
src/wiki/models/pluginbase.py
tests/core/test_models.py

I looked at the doc for pre_save signals and there is no indication of a "created" parameter. I made a test to show the issue.
Here is my fix + the test, the fix is base on the pre_save signals of attachements revision.

Fix presave

---

docs/release_notes.rst
src/wiki/__init__.py
src/wiki/forms_account_handling.py
tests/core/test_accounts.py

Add missed call to `super().clean()` to user signup view

---

tests/core/test_accounts.py
tests/core/test_basic.py
tests/core/test_views.py

These are based on flake8-assertive.

Improve a few asserts.

---

.github/ISSUE_TEMPLATES/bug_report.md

Mainly just adapted a bit from https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md

Add bug report issue template.

---

src/wiki/admin.py
src/wiki/views/article.py
tests/core/test_models.py

Hey folks, this is my first time contributing to this repository and I have noticed that there might be some scope for performance improvement in some areas.
To explore the same, I have written one test for `ArticleRevision` model and added it to [`tests/core/test_models.py`](https://github.com/Dev-Mehta/django-wiki/blob/Dev-Mehta-Optimization-Of-Queries/tests/core/test_models.py#L154-L189).
Can someone check the code and verify whether it is fine, if yes I can optimize queries for all models.
Sample Test Result:

Optimized ArticleRevision queries and added tests for the same

---

src/wiki/plugins/attachments/models.py

Changes for on_revision_delete to check to make sure len(path) != 0

Add path check for on revision delete

---

docs/release_notes.rst
src/wiki/plugins/attachments/templates/wiki/plugins/attachments/index.html
src/wiki/templates/wiki/includes/editor_sidebar.html
src/wiki/templates/wiki/includes/formfield.html
testproject/testproject/settings/dev.py

Fixes #1208 
I also added a few settings to the dev config in order to make it more easier for test with the local Django project.

Set the right class for collapse and form error

---

README.rst
src/wiki/views/mixins.py
tests/core/test_views.py

Use SHOW_MAX_CHILDREN in ArticleMixin

---

.circleci/config.yml
pyproject.toml

I'm not what's the most elegant way to re-enable this, but it seems like another sequence of commands was originally running in this step

Re-enable CodeCov?

---

pyproject.toml

Maybe it's useful to start commenting on why a dependency is there and what expectations we have for the versions that are pinned? What do you think @oscarmcm ? :)
Fixes #1252

Put an upper bound on bleach and comment each and every dependency

---

.github/ISSUE_TEMPLATE/config.yml

I didn't find the option to open an issue as a maintainer :)

Maybe we should allow this?

---

.github/DISCUSSION_TEMPLATE/bug-report.yml
.github/DISCUSSION_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue_template.md

Attempt to solve this:
And this:

Solve yml issues and improve issue templates

---

pyproject.toml
src/wiki/conf/settings.py
src/wiki/core/markdown/__init__.py

This is a continuation of #1253, an improved version of #1255, and fixes:
- #1259 
- #1257 
- #1251

Add support for the latest bleach version

---

README.rst

This mostly shortens and clarifies information in the README.
I removed the whole requirements section, maintaining information this way obviously doesn't work.
If you wonder about the inconsistent line breaking, I guess the whole document should be refactored to sembr.
More documentation work can be done for sure :+1:

Bunch of README updates

---

README.rst

This was what I originally wanted to have fixed in #1271.

More README updates: Add new demo info

---

docs/conf.py

Workaround for https://github.com/readthedocs/sphinx_rtd_theme/issues/1452

Docs: jQuery broken

---

.readthedocs.yml
pyproject.toml
requirements_readthedocs.txt

Duplicate the work made in https://github.com/django-wiki/django-nyt/pull/121

Improve Read The Docs configuration

---

docs/release_notes.rst

Translation updates

---

testproject/testproject/fixtures/fixtures.json

Grant more permission to the users

---

docs/installation.rst

Addresses https://github.com/django-wiki/django-wiki/discussions/1305

Docs: Add introduction to installation section

---

testproject/testproject/fixtures/fixtures.json

Upgrade fixtures for django-nyt 1.4

---

pyproject.toml

Discussed on:
- #1366
Attempt to fix:
- #1367
Likely related to:
- #1369

Use a pure python script for artifact build
