wiki/plugins/links/mdx/urlize.py
See: http://pythonconquerstheuniverse.wordpress.com/2012/02/15/mutable-default-arguments/
Worth a test case?
=> Properly sets default configs in plugins/links/mdx

wiki/core/http.py, wiki/decorators.py
Mimetype was completely removed in Django 1.7
=> Use content_type instead of mimetype

docs/customization.rst, wiki/templates/wiki/base_site.html
Added additional block to base template that allows overriding the site title (within <title> tag). Implements #387.
It's a fairly simple patch, although I'm not sure if it would be better to allow people to be able to override the entire <title> tag in one go. I'm assuming that most people won't want to do that, though, and just want to change the branding part.
=> Additional block for overriding branding in page title

wiki/templates/wiki/includes/article_menu.html
Before:
After: 
Looks the same for any size bigger than xs.
=> Hide article menu labels in mobile view

wiki/models/__init__.py
Without this import statement, `manage.py makemigrations` creates a new migration to delete all the plugin base models, because it cannot find them (see #399).
=> Import all models in models/__init__.py (fixes #399)

wiki/core/compat.py
The `User` model without `USERNAME_FIELD` attribute might get error in `PermissionsForm`.
=> Fixed the compatible with the `USERNAME_FIELD` for the Django version below 1.5.

wiki/core/http.py
PR #384 doesn't work with apache
Got
> embedded newline in response header with name 'Content-Disposition'
From Apache
=> Escape unicode filename while download attachment

wiki/managers.py, wiki/tests/__init__.py, wiki/tests/test_managers.py, wiki/tests/test_template_filters.py
OK, apologies in advance for a long tale...
First, I noticed that on Django 1.5 only 2 tests were running instead of 65. You can see this here:
https://travis-ci.org/django-wiki/django-wiki/jobs/66873647 (Django 1.5)
https://travis-ci.org/django-wiki/django-wiki/jobs/66873648 (Django 1.6)
The first commit fixes that.
Once the tests are running, there are test failures:
* one fairly straightforward one about striptags. This is fixed in the second changeset
* one nightmare causing an infinite recursion, and potential data loss bugs, due to `get_query_set` chaos.
This is addressed in the third changeset. Fixing it is tricky, but the pattern to use is given in the Django 1.6 release notes. https://docs.djangoproject.com/en/1.8/releases/1.6/#get-query-set-and-similar-methods-renamed-to-get-quer …
=> Django 15 fixes

docs/installation.rst
Tested with Django 1.8 + Python 3.4.2
=> Typo and missing import in installation instructions.

wiki/plugins/attachments/tests/test_views.py, wiki/plugins/attachments/views.py
This tweaks the replace attachment functionality to behave as discussed in issue #441.
=> Attachment upload tweak

wiki/plugins/mediawikiimport/management/commands/mediawiki_import.py
This fix multiples issues in the import script for mediawiki:
* `only_printable` was broken
* Switch from `%` to `format` syntax
* Fix unicode issues with `u""` (and `format`)
=> Fix errors in import script

wiki/urls.py
Fix a bug introduced in 0e3d363dcdc39167d652bcd1fe44d838df131cef where the function pointers to diff and merge view functions are attached as an instance method on the class instead of a staticmethod. This caused 'self' to be passed as first argument to these views, resulting in stacktraces for these views.
This was new to me, but attaching a function outside of the constructor of the class renders
that function to be declared as an instance method.
Performing the same operation inside the `__init__(self)` constructor will automatically yield a staticmethod.
Examples:
The following will produce an instancemethod:
```
def func(req, *args, **kargs):
pass
class MyClass(object):
some_view = func
```
Where a call to MyClass().some_view will have the following parameters: `(self, req, *args, …
=> Fix diff and merge AJAX call server errors

wiki/forms.py
This is in regards to issue #466. 
This PR changes the `EditForm` clean behaviour to throw a validation error when attempting to save something with no title, or with an all whitespace title.
=> Validate revision title

runtests.py, wiki/conf/settings.py, wiki/forms.py, wiki/migrations/0001_initial.py, wiki/models/article.py, wiki/tests/test_basic.py, wiki/tests/test_models.py, wiki/tests/testdata/models.py
This patch lets you use a custom `GROUP_MODEL` instead of the builtin `auth.Group`.
In a project of mine, we substituted `auth.Group` with our custom `groups.Group` model as injecting lots of functionality into `auth.Group` seemed like a big hack and it was easier this way. Unfortunately, this brings incompatibilities to 3rd party apps like this one.
This patch implements this functionality for Django 1.7 and up since it relies on `django.apps` for finding the `GROUP_MODEL` and I wasn't quite sure how to hack this change into south migrations. For Django < 1.7 it simply uses `auth.Group` despite the value of `GROUP_MODEL`.
=> Add option to use custom Group model with wiki

wiki/migrations/0001_initial.py
Models didn't appear in sync with migrations (created under Django 1.7) running Django 1.9
=> Add default arguments that Django 1.9 wants explicitly

wiki/decorators.py, wiki/plugins/attachments/models.py
I have absolutely no clue what the old code was trying to do. 
The relevant commit (791888eec2d64c80bb3abd0e43fbfcdb1b91a18a) seems to just update the code to the new exception syntax except for these two places. 
What it ended up doing was overwriting DoesNotExcept with an instance of another DoesNotExist. The next time this exception was supposed to be called it failed and created another exception (TypeError: 'DoesNotExist' object is not callable).
=> Undo weird old changes to exception handling

wiki/plugins/attachments/tests/test_views.py, wiki/plugins/attachments/views.py, wiki/templatetags/wiki_tags.py
Demo server error:
```
Internal Server Error: /Test/_plugin/attachments/search/
AttributeError at /Test/_plugin/attachments/search/
'AttachmentSearchView' object has no attribute 'get_form'
```
=> Fix 'AttachmentSearchView' object has no attribute 'get_form'

setup.py
This affects clean environments that were missing django-sekizai and had South needlessly installed.
=> Update default requirements when no Django yet installed

wiki/forms.py, wiki/templates/wiki/accounts/account_settings.html, wiki/templates/wiki/base_site.html, wiki/templatetags/wiki_tags.py, wiki/tests/test_managers.py, wiki/tests/test_template_filters.py, wiki/tests/test_views.py, wiki/urls.py, wiki/views/accounts.py
https://github.com/django-wiki/django-wiki/issues/490
Adds a simple page where users can change their password and email address. It looks like this:
I also fixed a small typo ("ArticlManagerTests" -> "ArticleManagerTests")
=> account settings page

docs/release_notes.rst, wiki/models/article.py, wiki/plugins/images/markdown_extensions.py, wiki/plugins/images/models.py, wiki/plugins/images/templates/wiki/plugins/images/index.html, wiki/plugins/images/templates/wiki/plugins/images/sidebar.html, wiki/plugins/images/tests/__init__.py, wiki/plugins/images/tests/test_views.py, wiki/plugins/images/views.py, wiki/plugins/images/wiki_plugin.py
Adds:
* Seemingly stubbed out (unimplemented feature) of setting the image revision finalized
Fixed:
* Deleting and restoring images in general was borked because the revision number wasn't set on the new revision #533
* Deleting and restoring images with current revision unset
=> Restore image restoring

wiki/plugins/haystack/__init__.py
Addressing:
File "/Users/neo/.virtualenvs/pp_new/lib/python3.5/site-packages/wiki/plugins/haystack/__init__.py", line 3, in <module>
from wiki.core import settings
ImportError: cannot import name 'settings'
Process finished with exit code 1
=> wiki.core doesn't have settings.py; In fact wiki.conf does

wiki/managers.py, wiki/views/article.py
If searching for articles while logged in, but without permissions to edit the article, the search returns duplicates.  More specifically it returns a duplicate for each member of the group the article is owned by.
This is because of the query produced by the many-to-many relation using `LEFT OUTER JOIN`. 
I read in an old issue that distinct was deliberately omitted because of performance issues so I only added it to the one place I know there is a bug.
Might be smarter to add it in `can_read` instead, but I'm not sure where the method is used and if it would lead to performance issues.
=> Fix duplicate search results

docs/release_notes.rst, setup.py, tox.ini, wiki/conf/settings.py, wiki/core/markdown/__init__.py, wiki/tests/test_markdown.py
Fixes #571 
Release notes added together with setting to customized whitelisted HTML tags.
=> Use Bleach to sanitize HTML and remove Markdown safe_mode

wiki/decorators.py, wiki/tests/test_views.py
Currently in django-wiki slugs must be lowercase. You can create a wiki link [[Like This]] in any page content, and the system redirects you to the create form if you click it (which is expected behaviour). However, the slug field is set to "Like_This", which fails validation because slugs must be lowercase.
This change lowercases the slug before the form loads, so that the user can proceed to add their new page without validation error.
Auto test added to `wiki/tests/test_views.py`
=> Lowercase slugs when creating new pages with [[Like This]].

Makefile, docs/release_notes.rst, wiki/core/utils.py, wiki/decorators.py, wiki/plugins/links/views.py, wiki/tests/test_utils.py, wiki/views/article.py
Fixes errors of this type:
```
Internal Server Error: /Test/tttt/dddd/_plugin/links/json/query-urlpath/
TypeError at /Test/tttt/dddd/_plugin/links/json/query-urlpath/
<HttpResponseNotFound status_code=404, "text/html; charset=utf-8"> is not JSON serializable
```
=> Refactor json_view, fixes 500 errors when looking up 404 paths

wiki/migrations/0001_initial.py
Removes this for `makemigrations` on current wiki 0.2 and 0.2.1 release:
```
Migrations for 'wiki':
0002_auto_20170319_0118.py:
- Alter field article on urlpath
```
=> Change verbose_name in migration to avoid django asking for migration updates

wiki/conf/settings.py
When adding two spaces at the end of lines markdown creates a \<br\> tag.
\<br\> needs to be allowed for that.
=> Allow the HTML tag <br>.

wiki/plugins/images/markdown_extensions.py, wiki/plugins/images/settings.py, wiki/plugins/images/templates/wiki/plugins/images/render.html, wiki/plugins/images/templates/wiki/plugins/images/sidebar.html, wiki/plugins/images/tests/test_views.py
Added a new option to specify the thumbnail size of images.
This patch is based on the work by inflrscns:
https://github.com/django-wiki/django-wiki/compare/master...inflrscns:thumbnail-sizes
Extensions compared to that version are:
- New image size "orig". No thumbnail is generated in this case, but the original image is shown instead.
- Updated image help in the sidebar.
The size can be specified by "size:small | medium | large | orig | default".
The small/medium/large/default sizes are configurable.
=> Added new image size option

requirements_readthedocs.txt, setup.py, wiki/plugins/links/mdx/djangowikilinks.py, wiki/tests/test_markdown_plugins.py
A URL like this one: `[Français](wiki:/fr)` seems to be crashing. The `config['base_url']` seems to be a Proxy object (See here: https://github.com/django-wiki/django-wiki/blob/master/wiki/plugins/links/wiki_plugin.py#L30) and when the wiki link is absolute, it crashes with a traceback like this:
This PR does the following:
1. Adds a test case to replicate the bug.
2. Fixes the bug by evaluating the lazy object
In addition I'm adding `,<1.11` to `setup.py` and requirements file because django-wiki doesn't currently support Django 1.11.
Useful part of the traceback:
```python
File "/home/b/projects/django-wiki/wiki/models/article.py" in render
209.                                           preview=preview_content is not None))
File …
```
=> Fixes issue where Markdown extension crashes when an absolute URL is used in a wiki link.

docs/release_notes.rst, wiki/core/markdown/mdx/codehilite.py, wiki/tests/test_markdown_plugins.py
Example:
```python
print("This will be highlighted")
```
=> Add support for Github flavored fenced code blocks

docs/release_notes.rst, wiki/conf/settings.py, wiki/core/markdown/__init__.py
Fixes #603
See: http://bleach.readthedocs.io/en/latest/clean.html#allowed-styles-styles
=> Setting `WIKI_MARKDOWN_HTML_STYLES` for allowing styles in user html

wiki/conf/settings.py
When placing three hyphens, asterisks, or underscores on a line by
themselves markdown creates a \<hr\> tag. \<hr\> needs to be allowed
for that.
=> Allow the HTML tag <hr>.

wiki/plugins/images/templates/wiki/plugins/images/sidebar.html
The current image insert procedure has different shortcomings.
- Does not allow to set the image size
- Does not check/help the user when setting the alignment
- Does not check the given alignment
- Two dialogs to get two values
This implementation replaces that with one bootstrapped dialog, which
allows to select the alignment and size via drop-down menus, and
creates always a valid and minimal tag (assuming of cause that the
caption is correct markdown).
=> New bootstrapped image insert dialog

wiki/tests/test_markdown_plugins.py
Just adding a test for TOC. I think the TOC codepath is already executed in some of the tests, but this adds a TOC-specific content assertion.
I want to add a horizontal TOC markdown plugin so I need to starts with some basic tests.
ping @benjaoming
=> Adds a functional test for the TOC plugin

.travis.yml, MANIFEST.in, Makefile, README.rst, runtests.py, setup.py, src/wiki/core/compat.py, src/wiki/editors/markitup.py, src/wiki/forms.py, src/wiki/templates/wiki/edit.html, tests/base.py, tests/core/test_managers.py, tests/core/test_markdown.py, tests/core/test_template_tags.py, tests/core/test_views.py, tests/plugins/attachments/test_commands.py, tests/plugins/attachments/test_views.py, tests/plugins/globalhistory/test_globalhistory.py, tests/plugins/images/test_views.py, tests/settings.py, tests/testdata/urls.py, tox.ini
This is a PR for Django 1.11 support, refs #614, using the approach described in
https://github.com/django-wiki/django-wiki/pull/624#issuecomment-298289218
I didn't start from #624 just because it was simpler to start from a clean sheet, and I had already done so.
Some additional notes, beyond what is the commit messages:
1. I did a fair bit of refactoring of test classes. This was basically because you have test base classes being used for two purposes - one is essentially fixture creation, the other is different types of test (Django client, WebTest, Selenium). To avoid combinatorial explosion of base classes, now most fixtures are provided by mixins which can be added to any test.
I also had to fix a fair few fragile tests.
2. I had to rename the existing 'WebTestBase' to …
=> Django 1.11 fixes

src/wiki/plugins/globalhistory/templates/wiki/plugins/globalhistory/globalhistory.html, src/wiki/plugins/globalhistory/views.py, src/wiki/plugins/globalhistory/wiki_plugin.py, tests/plugins/globalhistory/test_globalhistory.py
Added a new option to the global history plugin to
- show all revisions of all articles or to
- show only the last revision of every article.
Toggling between these two is as well possible on the global history
page via a button.
=> Global history: Show only last revision of every article

testproject/testproject/settings/base.py
Since Bootstrap 3 alert-error is renamed to alert-danger. As a result
messages.error() does not use by default the correct class anymore.
This PR changes the settings for the test project, so that that one
uses the alert-danger class.
=> Since Bootstrap 3 error messages must be shown with alert-danger

.travis.yml, docs/release_notes.rst, tox.ini
```
Trusty GCE images should now have Python 3.5 and 3.6 pre-installed.
sudo: required
dist: trusty
```
Also allows positional arguments to specify test, for instance:
tox -e py35-django110 tests/core/test_basic.py
Ref: #644
=> Python 3.5 and 3.6 are now available from travis images

tox.ini
@floemker this fixes the sudden test failures that we have been seeing lately
@spookylukey FYI, upping from WebTest 2.0.27 to 2.0.28 broke tests, so I had to exclude it. I'm not sure what causes the problem, but it's easy to reproduce (just remove the pinned version from tox.ini) - it seems that the login emulation doesn't work. Here's the changeset in WebTest: https://github.com/Pylons/webtest/compare/2.0.27...2.0.28
=> Fix tests by pinning test dependency WebTest

src/wiki/plugins/attachments/models.py
Restoring attachments does not work anymore since
0d84a9cb0093f0669f5a589c0cbb238b19c7a8b1,
as previous_revision is not set anymore for the new
revision when deleting the attachment. But that is needed for
restoring the attachment.  Line from the index.html template:
if attachment.current_revision.previous_revision.id
The reason seems to be that "created" is used in the pre_save attachment
hook to check if the instance was created or updated, but only the
post_save signal provides a created argument, not prev_save.
So for deciding if the instance is updated or created something else
needs to be used, e.g instance._state.adding.
=> Fix for "Restore attachments"

src/wiki/models/urlpath.py
django-mptt calls \_\_str\_\_() for an already deleted tree. Prevent in this
case a "Cannot call get_ancestors on unsaved URLPath instances" exception.
This is a work around for an MPTT bug which is needed till PR
django-mptt/django-mptt#591 from MPTT is included in all supported MPTT
versions.
This fixes the exception from issue  #668, but is of course only a work around
for the real bug in MPTT.
=> Don't access a deleted URLPath.

src/wiki/plugins/notifications/forms.py
The notifications plugin uses a ModelChoiceField in it's settings. A
ModelChoiceField needs as first argument a QuerySet or initially None,
not a Model. Since Django 1.11 the provided queryset is already used in
the \_\_init\_\_() function, resulting in an AttributeError when the wrong
type is used here.
This fixed issue #676.
=> Fix settings with Django 1.11

docs/settings.rst, src/wiki/conf/settings.py, src/wiki/plugins/attachments/settings.py, src/wiki/plugins/images/settings.py, src/wiki/plugins/links/settings.py, src/wiki/plugins/macros/settings.py
Use Sphinx compatible syntax for all wiki settings, including settings
from plugins, extended and corrected documentation for different wiki
settings, and extended the main settings page to include sections for
the different plugin settings.
This fixes issue #642.
=> Extended documentation for the wiki settings.

README.rst
I was looking through django-wiki and was surprised to find South
mentioned in the README and so started looking elsewhere. On closer
investigation South has been removed and so should not be mentioned.
Signed-off-by: Jamie Lennox <jamielennox@gmail.com>
=> Don't reference South in the README

src/wiki/templates/wiki/edit.html
When accidentally double clicking the "Save changes" button in the edit
form all requests are processed, resulting finally in an edit view with
A new revision of the article was successfully added.
on top and the error
While you were editing, someone else changed the revision. Your
contents have been automatically merged with the new contents. Please
review the text below.
next to it. Prevent this by allowing only one submit action in 3 seconds.
=> Prevent processing multiple edit submits in a row.

src/wiki/plugins/attachments/markdown_extensions.py, src/wiki/plugins/attachments/templates/wiki/plugins/attachments/index.html, src/wiki/plugins/attachments/templates/wiki/plugins/attachments/render.html, tests/plugins/attachments/test_views.py
Extended markdown syntax for attachments:
[attachment:id title:"text" size]
`title` and `size` are optional. If `title` is given it replaces the default link text, the
file name. If `size` is given the file size of the attachment is appended to the link text.
This is a superset of issue #214.
=> Extended attachment markdown macro.

src/wiki/forms.py
Currently the 'Summary' string in django-wiki collides with the same string in django-admin. It results in django-admin's version being used if `django.contrib.admin` was listed earlier in `INSTALLED_APPS`.
At least Russian translation of django-admin's 'Summary' string is quite bad. It may be the case for other languages too.
I didn't find a clean way to make a fallback to the previous translations. It means that 'Summary' won't be translated until new translation are added in transifex and exported to the django-wiki repository. Please tell me if you know how to do it.
=> Add context to the 'Summary' string

src/wiki/core/markdown/__init__.py, src/wiki/core/plugins/registry.py
some plugins already needs modify the bleach tags whitelist (plugins/images). This changeset add two options to a plugin class:
- `html_whitelist` - list of http tags to be added to bleach whitelist
- `html_attributes` - dictionary of http attributes to be added to bleach whitelist in the format
_http tag : [ allowed attributes ]_
=> allow plugins to modify Bleach tag lists

docs/release_notes.rst, src/wiki/models/urlpath.py
Causes linting errors, moreover would potentially cause an operation to unintentionally fail silently.
=> Remove delete_subtree bare except

src/wiki/plugins/attachments/views.py, src/wiki/plugins/images/views.py, src/wiki/views/article.py
When providing a list of results these results should be sorted to give
consistent results. Order search results and images by the time they
were changed and attachments by there name.
This fixes the Django 1.11
UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class '...'> QuerySet.
warning.
=> Sort search results, images, and attachments.

src/wiki/forms.py, src/wiki/plugins/attachments/forms.py
Not sure what the motivation for not calling clean, but you're missing out on all of django's built-in validation.
=> Call super().clean instead of accessing self.cleaned_data directly

src/wiki/managers.py
The performance of GROUP BY is much better on PostgreSQL
annotate(Count('id')) is the easiest way to generate GROUP BY id.
Tested on a wiki with about 22 000 revisions the SQL query difference is 33542ms vs 81ms when loading the globalhistory page. 
Preferably this should be tested on other setups too.
=> Replace distinct with GROUP BY id

.gitignore
https://www.python.org/dev/peps/pep-3147/ `__pycache__` overlaps with `*.pyc`, but I don't think it hurts to be explicit in `.gitignore`.
=> Added __pycache__ to .gitignore

src/wiki/templates/wiki/move.html
The recent pluralization introduced a small syntax error in the template code.
This fixes that.
=> Fixed template syntax error.

src/wiki/decorators.py, src/wiki/forms.py, src/wiki/models/urlpath.py, src/wiki/plugins/attachments/models.py, src/wiki/plugins/images/models.py, src/wiki/plugins/macros/mdx/toc.py, src/wiki/templatetags/wiki_tags.py, src/wiki/views/article.py
=> Removed six imports for built-ins.

src/wiki/templates/wiki/search.html
Since the addition of the "Searching in.../Searching whole..." label on the search
page the alignment of the search button compared to the search input field is off,
at least under Firefox. This patch moves the label out of the input-group, so that
the button and the input field are correctly aligned again.
Screen shot before (Firefox 57 under Linux):
Screen shot after (Firefox 57 under Linux):
=> Fixed alignment of the search button to the search input field.

src/wiki/conf/settings.py
The by default active footnote extension uses the \<sup> tag for
rendering the footnode. \<sup> needs to be allowed for that.
This fixes #749.
=> Allow the HTML tag <sup>.

src/wiki/migrations/0001_initial.py, src/wiki/models/article.py, src/wiki/models/pluginbase.py, src/wiki/models/urlpath.py, src/wiki/plugins/attachments/migrations/0001_initial.py, src/wiki/plugins/attachments/models.py, src/wiki/plugins/images/migrations/0001_initial.py, src/wiki/plugins/notifications/migrations/0001_initial.py, src/wiki/plugins/notifications/models.py
Added missing explicit on_delete on foreign keys.
(pr taken out from https://github.com/django-wiki/django-wiki/pull/755)
=> Explicit all on_delete on ForeignKey fields

src/wiki/plugins/attachments/migrations/0002_auto_20151118_1816.py, src/wiki/plugins/images/migrations/0002_auto_20151118_1811.py, src/wiki/plugins/notifications/migrations/0002_auto_20151118_1811.py
Add atomic flag for django >= 1.10, on django < 1.10 it does nothing.
(pr taken out from https://github.com/django-wiki/django-wiki/pull/755)
=> Set atomic = False for AlterModelTable migrations

.pre-commit-config.yaml, MANIFEST.in, docs/release_notes.rst, setup.py, wiki/__init__.py
Seems also that a couple of changes only made it to `master`, so they're included for the release tracking branch here as well...
=> django-nyt version cap for 0.2 series

docs/installation.rst, docs/plugins.rst, src/wiki/apps.py, src/wiki/conf/settings.py, src/wiki/core/plugins/loader.py, src/wiki/models/__init__.py, src/wiki/plugins/attachments/__init__.py, src/wiki/plugins/attachments/apps.py, src/wiki/plugins/globalhistory/__init__.py, src/wiki/plugins/globalhistory/apps.py, src/wiki/plugins/help/__init__.py, src/wiki/plugins/help/apps.py, src/wiki/plugins/images/__init__.py, src/wiki/plugins/images/apps.py, src/wiki/plugins/images/models.py, src/wiki/plugins/links/__init__.py, src/wiki/plugins/links/apps.py, src/wiki/plugins/macros/__init__.py, src/wiki/plugins/macros/apps.py, src/wiki/plugins/notifications/__init__.py, src/wiki/plugins/notifications/apps.py, src/wiki/templatetags/wiki_tags.py, tests/settings.py
Added app config for django-wiki and its default plugins and use the django apps machinery.
I've kept an import for existing plugins config in main apps.py.
(pr taken out from https://github.com/django-wiki/django-wiki/pull/755)
=> Added apps config

src/wiki/plugins/attachments/settings.py
The setting name does not match the expected name (dropped the "File") added this to docs and did not change the setting to preserve backward compatibility.
=> Small documentation fix

src/wiki/conf/settings.py
Code fixed to match documentation.
=> Fix wrong django setting name for MARKDOWN_HTML_ATTRIBUTES

docs/release_notes.rst, setup.py, src/wiki/__init__.py, src/wiki/models/article.py, src/wiki/models/pluginbase.py, src/wiki/models/urlpath.py, src/wiki/plugins/attachments/models.py, tox.ini
Also detect these problems in future PRs
Fix for non-default `on_delete` values specified in https://github.com/django-wiki/django-wiki/pull/759
Fixes #771
=> Fix missing migrations in 0.3.0 by reverting model changes

testproject/testproject/settings/base.py, testproject/testproject/settings/dev.py, testproject/testproject/urls.py, tests/settings.py, tests/testdata/urls.py
Exctract from https://github.com/django-wiki/django-wiki/pull/755
Use new MIDDLEWARE setting and urls include (django >= 1.11)
=> Remove deprecations

src/wiki/plugins/notifications/forms.py
The whole notifications plugin does not have any tests. Maybe this should be done in this PR, too?
=> Removed Django < 1.5 guard for list/QuerySet in SettingsModelForm.save.

.travis.yml, setup.py, tests/__init__.py, tox.ini
I'm testing django-wiki, and I need django 2 support :)
It needs https://github.com/benjaoming/django-nyt/pull/55 because I cannot monkey patch as I've done for django-mptt (already django 2 compatible on master) or django-functest (https://github.com/django-functest/django-functest/pull/14)
=> Django 2.0 support

src/wiki/apps.py, src/wiki/checks.py, src/wiki/compat.py, src/wiki/models/__init__.py, tests/core/test_checks.py
Move all configuration checks from `models/__init__.py` to the Django System check framework.
=> Move configuration check to django check framework

docs/release_notes.rst, src/wiki/conf/settings.py
Using short names for Markdown's builtin extensions is deprecated.
=> Use the full path to the markdown extension with Python's dot notation.

src/wiki/plugins/links/mdx/urlize.py, tests/plugins/links/test_urlize.py
This PR revamps the way the urlize markdown extension is implemented. It is *not* backwards compatible, though. While testing the old implementation, there was a number of issues I ran into (like lots of inline samples not working).
One of the big changes is that the link must be a standalone word (e.g. either at beginning/end of text or surrounded by spaces). This should help avoid some issues.
In general, though, one could see this extension (even the old implementation) as somewhat fragile/too optimistic. For example, if you have an OID 1.2.3.4, it'll get recognised as a link.
On a positive note, the extension has a bit more extensive tests in place now.
=> Fix urlize markdown extension

tox.ini
I'm not sure about keeping `! ` to accommodate Windows users.
=> Use --check option to check for test project's migrations.

docs/customization.rst, docs/installation.rst, docs/release_notes.rst, src/wiki/apps.py, src/wiki/conf/settings.py, src/wiki/sites.py, src/wiki/urls.py, testproject/testproject/urls.py, tests/core/test_sites.py, tests/testdata/urls.py
Removal of wiki.urls.get_pattern: introduce wiki.site similar to admin site.
It use the same strategy used for django admin default site https://github.com/django/django/commit/da3df5b878d96ef37dcff1377ccbd097b80776d7
=> Added WikiSite and deprecate wiki.urls.get_pattern

src/wiki/__init__.py
Was it the intention to leave out this? Because it kind of forces people to specify application configs, although there is a setting (also in Django 2.0) for this: https://docs.djangoproject.com/en/2.0/ref/applications/#for-application-authors
CC: @rsalmaso @atombrella
=> Add a default app config

src/wiki/plugins/macros/mdx/wikilinks.py, tests/plugins/macros/test_links.py
Please don't merge right away. I'm somewhat confused about the replication of the extension provided by `Markdown`, as it appears it's only due to the `md.article` bit.
There's also an option to configure the `html_class` which seems to be another reason for the duplication.
The shebangs are different places in the code-base, they shouldn't be needed. I removed it from the `wikilinks.py` file.
=> Added tests for the wikilinks plugin.

src/wiki/plugins/macros/templates/wiki/plugins/macros/sidebar.html
The safe filter was not applied because it was after the linebreak filter.
=> Change order of safe and linebreak in template

src/wiki/plugins/attachments/models.py, tests/plugins/attachments/test_models.py
`Field` has both `blank` and `null` set to `False`, so I believe this should be dead.
=>  Added some tests for the AttachmentRevision model.

docs/release_notes.rst, requirements_readthedocs.txt, setup.py
@last-partizan just to make sure, and trusting in the semantic versioning of the bleach team, we should use the series that we know to work. Is that okay for your purpose?
Also added a release note. Can release immediate as another 0.4 version...
=> Pin bleach >=2.1,<2.2

docs/installation.rst
`context_processors` in Django 1.10 and above has been moved from `core` to `template`.
(source: https://stackoverflow.com/a/44071228/196244 )
=> Update installation.rst: fix import

src/wiki/models/article.py, tests/core/test_basic.py
When a wiki page is edited from a browser, any non-DOS line endings will
be converted to DOS line endings \r\n. This creates an unnecessarily
large diff on the first edit in case the initial revision was created
programatically and with UNIX line endings \n.
=> Convert UNIX line endings to DOS in add_revision()

src/wiki/templatetags/wiki_tags.py, tests/core/test_template_filters.py
- Preserve case of content rather than keyword
- Highlight entire word in case of partial word matching
- Use str.find(), str.index() and str.rindex() instead of regexes
- Don't insert superfluous spaces in snippet
=> Tweak search result highlighting

src/wiki/plugins/images/models.py, tests/plugins/images/test_views.py
Fixes #911 
This fixes some code that may have been introduced through a merging issue. I don't know -- but it addresses something that was assumed fixed and is already in the changelog, so will not add it again :)
=> Fix image deletion issue caused by S3 storage fix

requirements_readthedocs.txt, setup.py, src/wiki/conf/settings.py, src/wiki/core/markdown/mdx/codehilite.py, src/wiki/core/markdown/mdx/previewlinks.py, src/wiki/core/markdown/mdx/responsivetable.py, src/wiki/plugins/attachments/markdown_extensions.py, src/wiki/plugins/images/markdown_extensions.py, src/wiki/plugins/links/mdx/djangowikilinks.py, src/wiki/plugins/links/mdx/urlize.py, src/wiki/plugins/macros/mdx/macro.py, src/wiki/plugins/macros/mdx/toc.py, src/wiki/plugins/macros/mdx/wikilinks.py, src/wiki/plugins/redlinks/mdx/redlinks.py, tests/plugins/links/test_urlize.py
[python-markdown](https://github.com/Python-Markdown/markdown) is now
at version 3.0.1. Some interfaces that were formerly deprecated
are now removed. Make corresponding changes here, notably:
- remove 'smart_strong'
- remove 'safe_mode' HTML (was not implemented)
- remove 'md_globals'
- fix positional argumenst (e.g. extensions=[])
- support InlineProcessor (instead of Pattern) in WikiLinks
=> Add support for markdown >= 3.0

docs/release_notes.rst, src/wiki/__init__.py
0.4 series is maintained in `releases/0.4.x` now
=> Bump to 0.5.dev

src/wiki/models/article.py
Detailed description in #930 
Base the caching key on the username of a User instead of the `__str__`, to increase compatibility with Django projects using Memcached as their caching service.
The default behavior of `__str__` is to use `get_username()`, but many projects choose to overwrite the method for their custom users to show the users full name.
=> Use User.get_username() for article cache instead of User.__str__

src/wiki/conf/settings.py, src/wiki/plugins/links/mdx/urlize.py, tests/plugins/links/test_urlize.py
All right, I'll try to correct the problems.
For now these are the ones that I have been able to notice
#927 
Everything works. I've tried it in the latest version of Django-wiki in its master branch. I previously used a different version of django-wiki, many things changed from mardown 3.
Note: I have not tested correctly
=> Fix the numbers are detected as TLD domains 

tests/core/test_accounts.py, tests/core/test_models.py, tests/core/test_template_filters.py, tests/core/test_views.py, tests/plugins/images/test_views.py
assertTrue and assertFalse should not be used to test for not None or None
values.
=> Changed assertTrue/assertFalse to better test methods.

src/wiki/conf/settings.py
=> Corrected permitted h-level tags.

docs/release_notes.rst, setup.py
=> Bump to Markdown 3.1 series

src/wiki/plugins/macros/mdx/toc.py
The usage was removed in https://github.com/django-wiki/django-wiki/commit/c9b7f0b7b370c21b52f8e6c937687e9edb1d748b#diff-916cdb5c7b700ddd753057b9b0945e86
=> Remove unused constant

src/wiki/plugins/editsection/views.py
There is a small typo in src/wiki/plugins/editsection/views.py.
Closes #1032
=> docs: Fix simple typo, occurances -> occurrences

docs/installation.rst
*  Issue of [ #1036 Change something in "installation.rst"](https://github.com/django-wiki/django-wiki/issues/1036#issue-590903102) is fixed
* Resolved two errors of the following:
```shell
SystemCheckError: System check identified some issues:
ERRORS:
?: (wiki.E009) needs sekizai.context_processors.sekizai in TEMPLATE['OPTIONS']['context_processors']
```
```shell
from django.core.urlresolvers import reverse_lazy
ImportError: No module named 'django.core.urlresolvers'
```
=> update docs/installation.rst for django 2.2+

docs/release_notes.rst, src/wiki/checks.py, tests/core/test_checks.py
Soften a check failure to not raise exceptions from template tag libraries too early.
This issue is quite rare, it's a copy of how django.contrib.admin has implemented this.
=> Soften a check failure 

setup.py, tests/plugins/images/test_views.py
This addresses #1081, but a final release will also be made - 0.7 however.
If anyone needs a 0.6.1, please provide necessary backport for the `releases/0.6.x` branch.
=> Bump to Django 3.1 in install_requires

src/wiki/plugins/attachments/settings.py
Small typo in the documentation here: https://django-wiki.readthedocs.io/en/latest/settings.html#wiki.plugins.attachments.settings.FILE_EXTENSIONS
=> doc: fix typo in attachments documentation

src/wiki/core/markdown/mdx/responsivetable.py, src/wiki/plugins/editsection/markdown_extensions.py, tests/plugins/editsection/test_editsection.py
2 problems are solved
#1094 
(r"\w+", header)) > (r"\w+", str(header)))
#1091
https://docs.python.org/3.9/whatsnew/3.9.html#removed
=> Editsection removed method .getchildren(), fix bytes-like object

testproject/testproject/settings/customauthuser.py
Fixes #1104
Upgrade test settings for the "customauthuser" test, invoke with with `manage.py --settings=testproject.settings.customauthuser`
=> Fix development settings for custom auth models / testdata app

docs/release_notes.rst, src/wiki/__init__.py, src/wiki/plugins/notifications/static/wiki/plugins/notifications/js/ui.js
This fixes an exploitation scenario of which an attacker through a very short domain name may inject a `<script>` tag into a notification message through an article's title field.
This is mitigated by the fact that the messages are truncated at 25 chars and that most servers are hopefully running CSP.
=> Security fix (XSS) - Build HTML elements for notifications safely

src/wiki/plugins/attachments/forms.py
fix 'unzip file' (checkbox, Create individual attachments for files in a .zip file - directories do not work.) function in the attachment upload form. Without this fix, the function would throw out exceptions "'AttachmentArchiveForm' object has no attribute 'zipfile'" and a file mode error . To test this fix, user would also need to enable .zip extension in settings.py of the django wiki project, such as the following: WIKI_ATTACHMENTS_EXTENSIONS = ['pdf', 'doc', 'odt', 'docx', 'txt','zip']
Exception 1 note:
Environment:
Request Method: POST
Request URL: http://127.0.0.1:5555/grammar-research/_plugin/attachments/
Django Version: 3.2.6
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions', …
=> fix unzip file error in the attachment upload form

docs/release_notes.rst, src/wiki/plugins/attachments/templates/wiki/plugins/attachments/search.html
=> Attachment search: Use exception-proof get_size when files deleted

setup.py
Error described here: https://stackoverflow.com/questions/69528842/an-error-while-trying-to-execute-tests-on-python-3-10-with-pytest
=> Update pytest due to TypeError: required field "lineno" missing from alias

.git-blame-ignore-revs
https://www.michaelheap.com/git-ignore-rev/
Probably other commit hashes can be added to this file.
It may be nice to update the contributor documentation as well, since you need to configure this individually (or you may do it globally).
Please upvote this issue: https://github.com/github/feedback/discussions/5033 since GitHub doesn't support this feature, and will clutter the blame-feature with such commits.
=> Add file with Git hash for black code style commit

.github/dependabot.yml
I think it became an opt-in feature of GitHub.
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates
=> Enable automatic dependabot PRs

src/wiki/templates/wiki/includes/pagination.html
As mentioned in issue  #1187, I have changed default pagination to look like the [Bootstrap pagination bar](https://getbootstrap.com/docs/4.3).  
The new default pagination bar looks like this:
=> Make pagination look like Bootstrap pagination. resolves #1187

docs/release_notes.rst, src/wiki/forms.py
If you serve the wiki through ngingx, the remote ip is always empty, so 
i added the HTTP_X_REAL_IP header ass an alternative.
=> Anonymous wiki through nginx (or other proxy)

src/wiki/core/markdown/mdx/codehilite.py
I faced same issue as https://github.com/django-wiki/django-wiki/issues/945 and I was wondering why its was not merged so I made a Pull Request inspired by these piece of codes : https://github.com/Python-Markdown/markdown/pull/727 and https://github.com/jenda1/django-wiki/commit/07ea6d3360cd54cbbebc5291d34d58c5f3e8453f
=> Fix double escaping of block code

src/wiki/templates/wiki/includes/move_tree.html
The dropdown in "move page" looks strange and is hard to use due to lack of margins. Adding `dropdown-item` to the outer `<li>` will fix that.
=> (minor) fix "move page" dropdown for Bootstrap 4

README.rst, src/wiki/plugins/links/mdx/urlize.py
There are small typos in:
- README.rst
- src/wiki/plugins/links/mdx/urlize.py
Fixes:
- Should read `initiated` rather than `initiatied`.
- Should read `inconsistencies` rather than `inconsitencies`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

.readthedocs.yml
Builds started breaking since setup.py was removed. This should make the package be installed with `pip` during the build :crossed_fingers:
=> Adds .readthedocs.yml

src/wiki/plugins/images/markdown_extensions.py, src/wiki/plugins/macros/mdx/macro.py
I already migrated my project on Python 3.11 and I don't want to rollback just for the wiki module so I tried to find a fix for #1232
I first tried to remove global inline flags from the macro and image regular expressions, and the exception was gone. Then I overrode init functions from `Pattern` children classes in order to re-add the removed flags in the `compile` function.
Unfortunately, I wasn't able to run tests with hatch (I am on Windows and it uses sh commands).
=> Fix #1232 : global flags not at the start of the expression at position 9

src/wiki/admin.py, src/wiki/editors/base.py, src/wiki/editors/markitup.py, src/wiki/forms.py, tests/core/test_editor.py
Sometimes it is useful to have the current revision in the editor widget instance, for example to create preview and upload links, autocomplete, ...
<textarea name="content"
data-upload-url='/wiki/my-page/_plugin/attachments/...'>
Previously, EditorBase had an instance attribute "instance", but that doesn't make sense (there is only one global instance of Editor) and wasn't ever filled anyway. This patch removes that, renames the "instance" parameter in get_widget()/get_admin_widget() to "revision" (to make clear what this parameter is) and fills it appropriately.
=> Pass current revision to Editor.get_widget()/get_admin_widget()

src/wiki/core/markdown/__init__.py, src/wiki/plugins/editsection/markdown_extensions.py, src/wiki/plugins/editsection/views.py, src/wiki/plugins/editsection/wiki_plugin.py, tests/plugins/editsection/test_editsection.py
The main problem of editsection is to find the correct location of the section to edit in the source. Previously, that was done with custom, regex-based parsing, but that fails when code blocks contain lines which look like a header (for example, python comments).
This patch uses another approach to find the correct sections. It uses extended versions of the BlockParsers responsible for creating headers, which annotate those headers with the consumed source block. Since we know now which input was responsible for generating the header, we can easily locate it in the markdown source.
=> Rework editsection plugin (fixes #1246)

.circleci/config.yml, .github/issue_template.md, pyproject.toml
Since support for Python 3.11 was finally added in #1234, this is a continuation of the work and finally have a new version that supports Python 3.11 (#1243, #1232)
=> Add environments for py3.11 and dj4.1

docs/release_notes.rst
I think the year was not set correctly in this place.
=> Fix Release Date for 0.10b1 in release_notes.rst

src/wiki/views/article.py
In class MergeView, add @method_decorator(xframe_options_sameorigin) in line 913 to avoid bug
=> Fix xframe_options_sameorigin bug in MergeView

src/wiki/plugins/macros/mdx/macro.py, src/wiki/plugins/macros/mdx/toc.py, tests/plugins/macros/test_toc.py
This is a rough draft attempt to resolve Issue: https://github.com/django-wiki/django-wiki/issues/1042
This is inspired by the existing code here: https://github.com/django-wiki/django-wiki/blob/918b354aabf23ae7c1612e9ac746d7c7905c137b/src/wiki/plugins/macros/mdx/toc.py#L16
It caches keyword arguments parsed by the MacroPattern class to a class variable in WikiTreeProcessorClass. Then the 'run' method maps these keyword arguments to the object's attributes before running 'super().run(doc)'. Afterward, it takes a tmp dictionary with the attribute's original values sets, then back and resets the cache that was set by MacroPattern.
I have attempted to follow the instructions for contributing. I used hatch test and lint before submitting, and I added several new tests for TOC. 
**NOTE**: The …
=> Update TOC macro to enable feature parity with Article List

pyproject.toml, src/wiki/core/markdown/mdx/codehilite.py, src/wiki/core/markdown/mdx/responsivetable.py, src/wiki/plugins/attachments/markdown_extensions.py, src/wiki/plugins/images/markdown_extensions.py, src/wiki/plugins/links/mdx/djangowikilinks.py, src/wiki/plugins/links/mdx/urlize.py, src/wiki/plugins/macros/mdx/macro.py, src/wiki/plugins/macros/mdx/toc.py, src/wiki/plugins/macros/mdx/wikilinks.py, tests/plugins/macros/test_toc.py
As per:
Discussion:  https://github.com/django-wiki/django-wiki/discussions/1312
Issue: https://github.com/django-wiki/django-wiki/issues/1197
Issue: https://github.com/django-wiki/django-wiki/pull/1274
This updates the Wiki requirements to Markdown 3.4.4
All tests pass on Python 3.8. I need to configure Hatch to see 3.9 and 3.10 (I am skipping 3.7 as it is deprecated). 
I also have yet to run the tests with Selenium, but I have experience in that just haven't yet. 
Appreciate any help and advice to see this PR through.
=> Python markdown 34 support

src/wiki/conf/settings.py
One line change in wiki/conf/settings.py to add "align" as a permitted attribute for td tags.
=> Update settings.py to allow align attributes in td tags

.circleci/config.yml
By uploading the report at each step, we will have the full coverage report. This can include various types of specific support for different Django/Python versions that we are testing against.
I think that this is the way to do it, inputs most welcome!
=> Combine CodeCov uploads in all test steps

testproject/testproject/fixtures/fixtures.json, testproject/testproject/middleware.py, testproject/testproject/settings/dev.py
Kept seeing this message 2-3-4 times on the demo. It must be something about how middleware works in relation to how many requests are made through the middleware before calling `get_messages` from the template.
I think if you call the middleware 3 times before ultimately rendering the template, the message is added 3 times before it's consumed.
=> Demo: Only display demo message once

.pre-commit-config.yaml, docs/conf.py, src/wiki/conf/settings.py, src/wiki/core/markdown/mdx/codehilite.py, src/wiki/decorators.py, src/wiki/migrations/0001_initial.py, src/wiki/plugins/attachments/models.py, src/wiki/plugins/editsection/markdown_extensions.py, src/wiki/plugins/editsection/views.py, src/wiki/plugins/images/models.py, src/wiki/plugins/macros/mdx/toc.py, src/wiki/plugins/macros/mdx/wikilinks.py, src/wiki/plugins/notifications/migrations/0001_initial.py, src/wiki/plugins/pymdown/templatetags/wiki_pymdown_tags.py, src/wiki/templatetags/wiki_tags.py, tests/core/test_views.py, tests/plugins/images/test_views.py, tests/plugins/notifications/test_views.py, tests/plugins/redlinks/test_redlinks.py
Just a draft... overlapping with some changes in #1337 - will re-run once that's merged and released.
Thanks for the tip @valberg
=> Add pyupgrade

src/wiki/plugins/links/mdx/djangowikilinks.py, tests/plugins/links/test_links.py
Maybe introduced in https://github.com/django-wiki/django-wiki/pull/1313
This has been causing errors in our django-wiki installation after upgrading to 0.11.
=> Fix attribute error

README.rst
Was using this for profile link validation.
However, PyPi rejects it:
```
The description failed to render for 'text/x-rst'. See https://pypi.org/help/#description-content-type for more information.                         
```
=> Remove reST raw directive - This made the upload fail on pypi

pyproject.toml
@oscarmcm there was a misconfiguration in this rather complex area... I noticed that the .css file was missing in the .whl.
I _think_ (not totally sure) that the right way is to say that our `pysass` command is enough to generate the artifacts in their right location. Additional management of artifacts isn't necessary.
I'm gonna go ahead and merge this now in order to get the release out, but I think it does the right thing :)
=> Hotfix before releasing: wiki-bootstrap.min.css missing in dist files

pyproject.toml
No release yet, but I was just about to do one, that's why I wanted #1375 with a hotfix.. which of course got rushed.
And sorry, this is gonna get confusing @oscarmcm 
I actually had some issues where I was missing pysassc, but after installing it, I still get the artifact in the wrong location.
(I had fixed that wrongly in the hotfix, too)
But it seems to produce everything fine now.
=> Fix the hotfix

src/wiki/plugins/attachments/templates/wiki/plugins/attachments/search.html
If someone managed to get something malicious into the DB we display it in the template. Similar issue to https://github.com/django-wiki/django-wiki/security/advisories/GHSA-f8hx-4ghf-5wg2
=> Another instance of using safe incorrectly
